micronaut:
  application:
    name: api
  security:
    authentication: session
netty:
  default:
    allocator:
      max-order: 3
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
elasticsearch.httpHosts: http://localhost:9200,http://127.0.0.2:9200
