micronaut:
  security:
    enabled: true
    intercept-url-map:
      - pattern: /swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /redoc/**
        httpMethod: GET
        access:
            - isAnonymous()
      - pattern: /rapidoc/**
        httpMethod: GET
        access:
            - isAnonymous()
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
  application:
    name: api
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
