micronaut:
  application:
    name: api
  security:
    authentication: session
    oauth2:
      clients:
        default:
          client-id: ${OAUTH_CLIENT_ID}
          client-secret: ${OAUTH_CLIENT_SECRET}
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
